FROM nginx:alpine

# Copiar los archivos del frontend
COPY ./src /usr/share/nginx/html
COPY ./assets /usr/share/nginx/html/assets

# Configuración personalizada de Nginx para manejar rutas SPA (opcional)
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]