services:
  etfpro-backend:
    build: ./backend
    network_mode: "host"
    environment:
      - TWELVE_DATA_API_KEY=${TWELVE_DATA_API_KEY}
      - TIINGO_API_TOKEN=${TIINGO_API_TOKEN}
    volumes:
      - ./backend/instance:/app/instance

  etfpro-frontend:
    build: ./frontend
    network_mode: "host"
    volumes:
      - ./frontend/src:/usr/share/nginx/html
      - ./frontend/assets:/usr/share/nginx/html/assets